spring.application.name=jobtrackr

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/jobtrackr
spring.datasource.username=postgres
spring.datasource.password=Uscollege@123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Port
server.port=8080
